- name: Install PHP and required modules
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - php
    - libapache2-mod-php
    - php-mysql

- name: Remove Apache default index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: Add PHP Info Page
  copy:
    dest: /var/www/html/index.php
    content: "<?php phpinfo(); ?>"
